ENH: Changed the takepeds to automatically pick a station
pcdshub/engineering_tools pull request #112
Opened 2022-03-03 02:04 UTC by aoluwade

## Description

Changed the "-p 0 -r" in the command to "get_info --getstation" 
## Motivation and Context

It automatically gets the station for the user as opposed to the default station 0 before.
## How Has This Been Tested?

it has not been tested.
## Where Has This Been Documented?

None.

2022-03-03 02:13 UTC, silkenelson approved these changes
While the commit message had be worried the '-r' was gone, the code looks good to me. I assume this was tested in the two CXI endstations?

2022-03-03 02:14 UTC, ZryletTC requested changes
Waiting on tests...
Could you also please add a usage? (look at other scripts for examples)

2022-03-04 22:09 UTC, aoluwade commented
> 
A usage function has been added.

2022-03-05 01:19 UTC, aoluwade commented
> Waiting on tests... Could you also please add a usage? (look at other scripts for examples)

Tested on cxi-daq and cxi-monitor and it works.

2022-03-05 01:29 UTC, ZryletTC approved these changes

2022-03-05 01:29 UTC, ZryletTC commented on scripts/takepeds
> +Generates the background (dark) image and the noise values for each pixel, and posts to the elog.
```suggestion
Takes a run with dark images for use in pedestals, and posts to the elog.
```

2022-03-05 02:26 UTC, merged